config/routes.rb
      resources :reports, only: [:index] do
        collection do
          match :calls, via:[:get, :post]
          match :sms_list, via:[:get, :post], as: :sms
          match :url, via:[:get, :post]
          match :aggregates, via:[:get, :post]
          post :create_portal_session
          post :logout_portal_session
        end
      end
      resources :customers do
        collection { post :import }
        collection { post :get_contact }
        collection { post :send_phone_info }
        # post "exception_list" => "customers#exceptions"
      end
    end
  end

  match 'customers/exception_list' => 'customers#exceptions', :via => :post
  match 'customers/delete_multiple' => 'customers#destroy_multiple', :via => :post

  namespace :api, defaults: { format: :json } do
    scope :v1 do
      resources :sessions, only: [:create]
      resources :resources, only: [:index]
      resources :services, only: [:index]
      resources :preferences, only: [:index]
      resources :availability, only: [:index]
      resources :appointments, only: [:index, :create, :update, :destroy]
      resources :templates, only: [:index, :create]
      resources :customers, only: [:index, :create] do
        collection do
          match :auth_consumer, via: [:get, :post]
        end
      end
      get '/sessions', to: 'sessions#read'
      post '/send_email', to: 'sessions#send_email'
    end
  end

  resources :contact_us
  resources :clients do
    resources :ivrs do
      collection do
        get :change_ivr
      end
    end
    member do
      match :billing, via: [:post, :get]
      match :scheduling_appoinments_show, via: [:post, :get]
      match :edit_text, via: [:post, :get]
    end
    collection do
      patch :agenda_sign_up
      match :call_forwarding, via: [:post, :get]
      match :phone, via: [:get, :post]
      post :change_menu
      post :update_gtm_trigger
      post :get_client_detail
      get :my_ivrs
    end
  end

    resources :timify_credential, only: [] do
      collection do
        get :timify_cred
        post :timify_cred
        post :new_account_cred
        get :same_client
        get :different_client
        get :cancel_process
        get :check_timify_connection
        post :disconnect_timify_connection
      end
    end

  resources :integrations, only: [:index] do
    collection do
      match :connect_your_agenda, via:[:get, :post]
      match :select_agenda, via:[:get, :post]
      match :select_mobminder, via:[:get, :post]
      match :select_timify, via:[:get, :post]
      match :phone, via:[:get, :post]
      match :sms, via:[:get, :post]
      match :get_sms_channel, via:[:get]
      match :alpha_sms, via:[:get, :post]
      match :disconnect_calendar, via:[:post]
      match :update_calendar, via:[:post]
      match :update_conflict, via:[:post]
      match :change_dataserver, via:[:post]
      match :inbound_sms, via:[:post]
    end
  end

  resources :appoinments_scheduling, only: [:index, :create] do
    collection do

      get '/widget_preference/:ivr_id', to: 'appoinments_scheduling#widget_preference', as: 'widget_preference'
      get '/assistant_preference/:ivr_id', to: 'appoinments_scheduling#assistant_preference', as: 'assistant_preference'
      get '/general_preference/:ivr_id', to: 'appoinments_scheduling#general_preference', as: 'general_preference'
      get :get_resources
      match :assistant_preference, via:[:get]
      match :service_and_resource, via:[:get, :post]
      match :custom_texts, via:[:get, :post]
      match :save_language, via:[:post]
      match :save_business_hours, via:[:post]
      match :save_welcome_message, via:[:post]
      match :save_announce, via:[:post]
      match :save_followup, via:[:post]
      match :save_preferences, via:[:post]
      match :save_custom_texts, via:[:post]
      match :save_phone_menu, via:[:post]
      match :save_phone_menu_extentions, via:[:get, :post]
      match :new_phone_menu_extention, via:[:get]
      match :get_phone_menu_extention, via:[:get]
      match :get_extension, via:[:get]
      match :save_extension, via:[:post]
      match :delete_phone_menu_extension, via:[:post]
      match :remove_extension, via:[:post]
      match :set_default_extension, via:[:post]
      match :save_widget_setting, via:[:post]
      match :save_booking_option, via:[:post]
      match :save_branding, via:[:post]
      match :save_general_setting, via:[:post]
    end
  end

  resources :schedule_event do
    collection do
      post :get_events
      post :get_event_detail_info
      post :delete_event
      post :save_setting
      post :save_business_hours
      post :get_time_list
    end
  end

  resources :availablities do
    collection do
      post :save_schedule
      post :clone_schedule
      post :set_as_default
      post :delete_schedule
      post :save_availability
    end
  end

  resources :resources do
    member do
      put :toggle_enabled, as: :toggle_enabled
      post :change_enabled, as: :change_enabled
      post :get_calendar_info_of_resource
    end

    collection do
      post :get_availablities
      post :get_calendar_info_of_default
      post :update_resource
    end
  end
  resources :services do
    member do
      put :toggle_enabled, as: :toggle_enabled
      put :toggle_service_options_enabled, as: :toggle_service_options_enabled
    end

    collection do
      get '/new', to: 'services#new', as: :new_service
      get '/new_event/:ivr_id', to: 'services#new_event', as: :new_event
      get '/edit_event/(:id)', to: 'services#edit_event', as: :edit_event
      post :update_ordering, as: :update_ordering
      post :get_resources_of_selected_service, as: :get_resources_of_selected_service
      post :save_agenda_service_resource
      post :get_availablities
      post :save_as_schedule
      post :save_automation
      post :get_automation
      post :save_question
      post :automation_enabled
      post :get_slot_example
      post :number_list
      post :get_phone_countries
      post :order_number
      post :buy_no_address_number
      post :set_phone_type_of_ivr
      post :set_read_tutorial
      get :get_dependencies
      get '/(:filter)', to: 'services#index', as: :services
    end
  end

  resources :profiles do
    collection do
      post :close_account
      post :update_locale
      get :closed_account
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #root 'clients#dashboard'
  get '/dashboard', to: 'clients#dashboard'
  get '/onboarding', to: 'home#onboarding'
  get '/old_onboarding', to: 'home#old_onboarding'
  get '/member_onboarding', to: 'home#member_onboarding'
  get '/set_server_region', to: 'home#set_server_region'
  get '/set_server_region_member', to: 'home#set_server_region_member'
  get '/verification_init', to: 'home#verification'
  get '/settings', to: 'clients/ory#reset'
  get '/recovery', to: 'clients/ory#recovery'
  get '/send_verification/:id', to: 'profiles#send_verification', as: :send_verification
  root 'home#index'
  match '/sms', to: 'webhooks#sms_webhook', via: [:get, :post]
  post '/recovery_client', to: 'clients/ory#recovery_client'
  get '/invitation/:id', to: 'clients/ory#invitation'
  get '/verification', to: 'clients/ory#verification'
  get '/ory_init', to: 'clients/ory#ory_init'
  get '/ory_error', to: 'clients/ory#error'
  get '/default_init', to: 'migration#default_init'
  get '/migrate_chargebee', to: 'migration#migrate_chargebee'
  get '/migrate_reminder_time', to: 'migration#migrate_reminder_time'
  get '/migrate_agenda_app_organization', to: 'migration#migrate_agenda_app_organization'
  get '/remove_clients', to: 'migration#remove_clients'
  get '/migrate_phone_info', to: 'migration#migrate_phone_info'
  get '/migrate_service', to: 'migration#migrate_service'
  get '/migrate_resource', to: 'migration#migrate_resource'

  get '/post_login', to: 'home#post_login'
  get '/post_registration', to: 'home#post_registration'
  get '/post_logout', to: 'home#post_logout'
  get '/post_settings', to: 'clients/ory#post_settings'
  get '/signup', to: 'clients/signup#new'
  get '/signin', to: 'clients/sessions#new'
  get '/logout_client', to: 'clients/ory#logout'
  post '/registration', to: 'clients/ory#registration'
  post '/check_email', to: 'home#check_email'
  post '/save_voxiplan_url', to: 'agenda_apps#save_voxiplan_url'
  post '/profile-edit', to: 'profiles#edit_profile'
  post '/set_organization', to: 'organizations#set_organization', as: :set_organization

  resources :webhooks, only: [] do
    collection do
      match :rasa, via: :all
      match :tropo, via: :all
      match :recording, via: :all
      match :timify_auth, via: :all
      match :voxi_sms, via: :all
      # match :twilio_sms, via: :all
      match :sms, via: :all
      # match :twilio_sms_status, via: :all
      # match :perform, via: :all
    end
  end

  resources :recordings, only: [:show]

  resources :automations do
  end

  # match '/recording', :to => 'webhooks#recording', via: [:all]
  match '/run/(:id)', :to => 'ivr#run', via: [:get, :post], as: :run_node
  get '/phone', to: redirect('voxiphone/index.html')
  get '/:id' => "shortener/shortened_urls#show"

  match '/s/:id', :to => 'chat#appointment', via: [:get], as: :appointment_widget

  # TODO: Only allow requests from Tropo
  scope format: true, constraints: { format: 'json' } do
    match '/welcome', :to => 'ivr#welcome', via: :post
    match '/menu1', :to => 'ivr#menu1', via: :post
    match '/handle_menu1', :to => 'ivr#handle_menu1', via: :post
    match '/handle_menu2', :to => 'ivr#handle_menu2', via: :post
    match '/handle_menu3', :to => 'ivr#handle_menu3', via: :post
    match '/create_appointment_with_phone', :to => 'ivr#create_appointment_with_phone', via: :post
    match '/send_sms', :to => 'ivr#send_sms', via: :post
    match '/receive_sms', :to => 'ivr#receive_sms', via: :post

app/views/home/_onboarding_availability.html.erb
<!--begin::Wrapper-->
<div class="w-100">
  <!--begin::Heading-->
  <div class="pb-10 pb-lg-12">
    <!--begin::Title-->
    <h2 class="fw-bolder text-dark"><%= t('onboarding.set_availability.title') %></h2>
    <!--end::Title-->
    <!--begin::Notice-->
    <div class="text-muted fw-bold fs-6"><%= t('onboarding.set_availability.title_description') %></div>
    <!--end::Notice-->
  </div>
  <!--end::Heading-->

  <div id="availability_customize_content" >
    <div class="card card-bordered">
      <div class="card-body p-0">
        <div class="row gx-0">
          <div class="col-md">
            <%= render 'shared/availability_week', availability: @customize_availability %>
          </div>
        </div>
      </div>

      <button type="submit" class="btn btn-outline btn-outline-primary btn-color-primary btn-active-color-white ms-5 d-none" id="save_default_hours"><%= t('button.save') %></button>
    </div>
  </div>

</div>
<!--end::Wrapper-->

app/views/home/_onboarding_general.html.erb
<!--begin::Wrapper-->
<div class="w-100">
  <!--begin::Heading-->
  <div class="pb-10 pb-lg-15">
    <!--begin::Title-->
    <h2 class="fw-bolder d-flex align-items-center text-dark"><%= t('onboarding.general_info.title') %></h2>
    <!--end::Title-->
    <!--begin::Notice-->
    <div class="text-muted fw-bold fs-6"><%= t('onboarding.general_info.title_description') %></div>
    <!--end::Notice-->
  </div>
  <!--end::Heading-->
  <!--begin::Input group-->
  <div class="fv-row mb-10">
    <!--begin::Label-->
    <label class="form-label required"><%= t('onboarding.general_info.organization_name') %></label>
    <!--end::Label-->
    <!--begin::Input group-->
    <div class="input-group input-group-solid input-group-lg">
      <input name="organization_name" type="text" class="form-control" id="organization_name" />
    </div>
    <div class="fv-plugins-message-container invalid-feedback" id="name_not_empty_message"><%= t('validation.not_empty') %></div>
    <!--end::Input group-->
    <div class="form-text"><%= t('onboarding.general_info.organization_name_description') %></div>
  </div>
  <!--end::Input group-->
  <!--begin::Input group-->
  <div class="fv-row mb-10">
    <!--begin::Label-->
    <label class="form-label required"><%= t('onboarding.general_info.create_url') %></label>
    <!--end::Label-->
    <!--begin::Input group-->
    <div class="input-group input-group-solid input-group-lg">
      <span class="input-group-text" id="basic-addon1">voxiplan.com/s/</span>
      <input name="voxiplan_url" type="text" class="form-control" id="voxiplan_url" ivr_id="<%= current_client.ivrs.first.id %>" style="text-transform: lowercase" />
    </div>
    <div class="fv-plugins-message-container w-100 text-success" style="font-size: 0.925rem;" id="available_message"><%= t('validation.available') %></div>
    <div class="fv-plugins-message-container invalid-feedback" id="unavailable_message"><%= t('validation.unavailable') %></div>
    <div class="fv-plugins-message-container invalid-feedback" id="url_not_empty_message"><%= t('validation.not_empty') %></div>
    <div class="fv-plugins-message-container invalid-feedback pr-3 detected_key_message" id="detected_key_message" style="font-weight: 600; margin-top: 0.3rem;"><%= t('validation.detected_key') %></div>
    <!--end::Input group-->
    <div class="form-text"><%= t('onboarding.general_info.create_url_description') %></div>
  </div>
  <!--end::Input group-->
  <!--begin::Input group-->
  <div class="fv-row">
    <!--begin::Label-->
    <label class="form-label required"><%= t('onboarding.general_info.timezone') %></label>
    <!--end::Label-->
    <!--begin::Input-->
    <%= select_tag "timezone", {}, class: "form-select form-select-solid form-select-lg", data: { control: 'select2', placeholder: 'Select a timezone' }, required: true %>
  </div>
  <!--end::Input group-->
</div>
<!--end::Wrapper-->

<!--Change voxiplan url with organization name -->
<script>
    $('.fv-plugins-message-container').hide();

    const default_timezone = "Europe/Paris";
    let selected_timezone = default_timezone
    let user_timezone = "<%= current_client.time_zone %>";
    let timezone = moment.tz.names();

    for (let i = 0; i < timezone.length; i++) {
        $("select#timezone").append(
            '<option value="' + timezone[i] + '">' + timezone[i] + "</option>"
        );
        if (user_timezone == timezone[i]) selected_timezone = user_timezone;
    }
    $("select#timezone").select2();
    $("select#timezone").select2().val(selected_timezone).trigger('change');

    function check_valid_voxiness_url(booking_url) {
        if (booking_url) {
            $.ajax({
                type: "POST",
                url: "/check_exist_ivr_url",
                data: { voxiplan_url: booking_url.toLowerCase().replace(/ /g, '').replace(/\?/g, '').replace(/\//g, '').replace(/&/g, ''), ivr_id: <%= current_client.ivrs.first.id %> },
                success: function (data) {
                    if (data.existed) $('#unavailable_message').show();
                    else {
                        $('.invalid-feedback').hide();
                        $('#available_message').show();
                    }
                },
                error: function (error) {
                    $.notify({ title: "<strong>Error!</strong>", message: "Something Went Wrong! Please Try again." },{ type: 'danger' });
                },
            });
        }
    };

    $('#voxiplan_url').on('keypress', function(e) {
        $('.fv-plugins-message-container').hide();

        if (e.which == 32 || e.which == 38 || e.which == 47 || e.which == 63) {
            e.preventDefault();
            $(this).parent().parent().find('.detected_key_message').show();
        }
    });

    $('#voxiplan_url').on('keyup', function(e) {
        if (!$(this).val()) $('#url_not_empty_message').show();
    });

    $('#organization_name').on('keyup', function() {
        $('#voxiplan_url').val($(this).val().replace(/ /g, '').replace(/&/g, '').replace(/\?/g, '').replace(/\//g, ''));
        $('.fv-plugins-message-container').hide();
        if (!$(this).val()) {
            $('#name_not_empty_message').show();
            $('#url_not_empty_message').show();
        }
    });

    $('#organization_name').on('change', function() {
        check_valid_voxiness_url($(this).val());
    });

    $('#voxiplan_url').on('change', function() {
        check_valid_voxiness_url($(this).val());
    });
</script>

app/views/home/_onboarding_welcome.html.erb
<div class="w-100 text-center">
  <!--begin::Heading-->
  <h1 class="fw-bolder text-dark mb-3"><%= t('onboarding.welcome.title') %></h1>
  <!--end::Heading-->
  <!--begin::Description-->
  <div class="text-muted fw-bold fs-3"><%= t('onboarding.welcome.title_description') %></div>
  <!--end::Description-->
  <!--begin::Illustration-->
  <div class="text-center px-4 py-15">
    <img src="/assets/onboarding/todo.png" alt="Todo" class="mw-100 mh-150px" />
  </div>
  <!--end::Illustration-->
</div>

app/views/home/onboarding.html.erb
<!--begin::Authentication - Sign-up -->
<div class="d-flex flex-column flex-column-fluid bgi-position-y-bottom position-x-center bgi-no-repeat bgi-size-contain bgi-attachment-fixed">
  <!--begin::Content-->
  <div class="d-flex flex-center flex-column flex-column-fluid p-10 pb-lg-20">
    <!--begin::Logo-->
    <a href="/" class="mb-12">
      <img alt="Logo" src="/assets/voxi_logo.png" class="h-45px" />
    </a>
    <!--end::Logo-->
    <!--begin::Wrapper-->
    <div class="bg-body rounded shadow-sm p-10 p-lg-15 mx-auto">
      <!--begin::Stepper-->
      <div class="stepper stepper-pills stepper-column d-flex flex-column flex-xl-row flex-row-fluid" id="kt_create_account_stepper">
        <!--begin::Aside-->
        <div class="d-flex justify-content-center bg-body rounded justify-content-xl-start flex-row-auto w-100 w-xl-300px me-9">
          <!--begin::Nav-->
          <div class="stepper-nav">
            <!--begin::Step 1-->
            <div class="stepper-item current" data-kt-stepper-element="nav">
              <!--begin::Line-->
              <div class="stepper-line w-40px"></div>
              <!--end::Line-->
              <!--begin::Icon-->
              <div class="stepper-icon w-40px h-40px">
                <i class="stepper-check fas fa-check"></i>
                <span class="stepper-number">1</span>
              </div>
              <!--end::Icon-->
              <!--begin::Label-->
              <div class="stepper-label">
                <h3 class="stepper-title"><%= t('onboarding.general_info.menu_name') %></h3>
                <div class="stepper-desc fw-bold"><%= t('onboarding.general_info.menu_description') %></div>
              </div>
              <!--end::Label-->
            </div>
            <!--end::Step 1-->
            <!--begin::Step 2-->
            <div class="stepper-item" data-kt-stepper-element="nav">
              <!--begin::Line-->
              <div class="stepper-line w-40px"></div>
              <!--end::Line-->
              <!--begin::Icon-->
              <div class="stepper-icon w-40px h-40px">
                <i class="stepper-check fas fa-check"></i>
                <span class="stepper-number">2</span>
              </div>
              <!--end::Icon-->
              <!--begin::Label-->
              <div class="stepper-label">
                <h3 class="stepper-title"><%= t('onboarding.connect_calendar.menu_name') %></h3>
                <div class="stepper-desc fw-bold"><%= t('onboarding.connect_calendar.menu_description') %></div>
              </div>
              <!--end::Label-->
            </div>
            <!--end::Step 2-->
            <!--begin::Step 3-->
            <div class="stepper-item" data-kt-stepper-element="nav">
              <!--begin::Line-->
              <div class="stepper-line w-40px"></div>
              <!--end::Line-->
              <!--begin::Icon-->
              <div class="stepper-icon w-40px h-40px">
                <i class="stepper-check fas fa-check"></i>
                <span class="stepper-number">3</span>
              </div>
              <!--end::Icon-->
              <!--begin::Label-->
              <div class="stepper-label">
                <h3 class="stepper-title"><%= t('onboarding.set_availability.menu_name') %></h3>
                <div class="stepper-desc fw-bold"><%= t('onboarding.set_availability.menu_description') %></div>
              </div>
              <!--end::Label-->
            </div>
            <!--end::Step 3-->
          </div>
          <!--end::Nav-->
        </div>
        <!--begin::Aside-->
        <!--begin::Content-->
        <%= form_for(current_client.agenda_apps, as: :agenda_app, :url => save_agenda_info_agenda_app_path, method: :post, html: {class: "w-100 w-lg-800px", id: "kt_create_account_form"}) do |f| %>
        <div class="d-flex flex-row-fluid flex-center bg-body rounded">
          <!--begin::Form-->

            <!--begin::Step 1-->
            <div class="w-100 <%= params[:success].present? ? 'completed' : 'current' %>" data-kt-stepper-element="content">
              <%= render 'onboarding_general' %>
            </div>
            <!--end::Step 1-->
            <!--begin::Step 2-->
            <div class="w-100 <%= params[:success].present? ? 'current' : '' %>" data-kt-stepper-element="content">
              <%= render 'onboarding_connect', form: f %>
            </div>
            <!--end::Step 2-->
            <!--begin::Step 3-->
            <div class="w-100" data-kt-stepper-element="content">
              <%= render 'onboarding_availability' %>
            </div>
            <!--end::Step 3-->

        </div>
        <!--begin::Actions-->
        <div class="d-flex flex-stack pt-10">
          <!--begin::Wrapper-->
          <div class="mr-2">
            <button type="button" class="btn btn-lg btn-light-primary me-3" data-kt-stepper-action="previous">
              <%= t('common.button.back') %>
            </button>
          </div>
          <!--end::Wrapper-->
          <!--begin::Wrapper-->
          <div>
            <button type="submit" class="btn btn-lg btn-primary me-3" data-kt-stepper-action="submit">
              <span class="indicator-label"><%= t('common.button.finish') %></span>
              <span class="indicator-progress"><%= t('common.please_wait') %>
                <span class="spinner-border spinner-border-sm align-middle ms-2"></span>
              </span>
            </button>
            <button type="button" class="btn btn-lg btn-primary" data-kt-stepper-action="next">
              <%= t('common.button.continue') %>
            </button>
          </div>
          <!--end::Wrapper-->
        </div>
        <!--end::Actions-->
        <% end %>
        <!--end::Form-->
        <!--end::Content-->
      </div>
      <!--end::Stepper-->
    </div>
    <!--end::Wrapper-->
  </div>
  <!--end::Content-->
</div>
<input type="hidden" id="ok_got_it" value="<%= t('sweetalert.ok_got_it') %>" />
<input type="hidden" id="normal_error_text" value="<%= t('common.normal_error_text') %>" />

<%= javascript_include_tag 'onboarding', 'data-turbolinks-track' => true %>
<!--begin::Page Custom Javascript(used by this page)-->
<script>
    $('input').keydown(function(event){
        if(event.keyCode == 13) {
            event.preventDefault();
            return false;
        }
    });

    // Input Mask
    (function () {
        const $from = document.querySelectorAll(".mask-from");
        const $to = document.querySelectorAll(".mask-to");

        Inputmask({
            alias: 'datetime',
            inputFormat: 'H2:MM',
            placeholder: '00:00',
            min: '00:00',
            max: '23:59'
        }).mask($from);

        Inputmask({
            alias: 'datetime',
            inputFormat: 'H2:MM',
            placeholder: '00:00',
            min: '00:00',
            max: '23:59',
        }).mask($to);
    })();

    $('button.btn-connect').on('click', function() {
        const provider_name = $(this).data('provider-name');
        const auth = $('[name="csrf-token"]')[0].content;
        $.ajax({
            url: "/agenda_app/create_new_agenda",
            type: "POST",
            data: {
                authenticity_token: auth,
                browser_locale: "<%= @browser_locale %>"
            },
            success: function(response){
                window.location.href = response.cronofy_auth_url + "&provider_name=" + provider_name + "&state=<%= SecureRandom.hex(24) %>" + "&locale=" + response.user_locale;
            }
        });
    })

</script>
<!--end::Page Custom Javascript-->
<!--end::Javascript-->
</body>
<!--end::Body-->
</html>

app/views/home/verification.html.erb
<style>
    #send_verification {
        color: #1B72E8;
        font-weight: 600;
        border: none;
        background: none;
    }
</style>
<div class="d-flex flex-column flex-column-fluid bgi-position-y-bottom position-x-center bgi-no-repeat bgi-size-contain bgi-attachment-fixed">
  <div class="d-flex flex-center flex-column flex-column-fluid p-10 pb-lg-20">
    <div class="bg-body rounded shadow-sm p-10 p-lg-15 mx-auto w-100 w-lg-75">
      <%= form_for('', url: send_verification_path(''), :html => {method: :post, role: 'form', :class => 'form w-100'}) do |f| %>
        <%= flash_messages %>
        <div class="stepper stepper-pills stepper-column d-flex flex-column flex-xl-row flex-row-fluid" id="kt_create_account_stepper">
          <div class="d-flex flex-row-fluid flex-center bg-body rounded">
            <div class="w-100">
              <div class="pb-2 pb-lg-4 text-center">
                <a href="/" class="mb-12">
                  <img alt="Logo" src="/assets/voxi_logo.png" class="h-45px" />
                </a>
                <%= f.hidden_field(:preferred_locale, id: "preferred_locale_hidden") %>
                <h2 class="fw-bolder text-dark mt-10"><%= t('verification.title') %></h2>
                <div class="text-muted fw-bold fs-6 mt-6"><%= t('verification.first_content') %></div>
                <div class="text-muted fw-bold fs-7 mt-2"><%= t('verification.second_content') %> <span class="text-dark fw-bold"><%=current_client.email %></span>? <a href="<%=ENV['ORY_URL'] + '/self-service/verification/browser' %>" id="send_verification"><%= t('verification.try_again') %></a></div>
                <div class="text-center mt-6">
                  <!--begin::Menu-->
                  <div class="menu menu-rounded menu-column menu-gray-600 menu-state-bg fw-semibold w-80px" data-kt-menu="true" style="float:right">
                    <div class="menu-item" data-kt-menu-trigger="hover" data-kt-menu-placement="bottom-end">
                      <a href="#" class="menu-link py-3 bg-hover-light-primary">
                        <span class="menu-title text-primary"><%= t('locales.' + (I18n.locale.to_s || 'en')) %></span>
                      </a>
                      <%= render 'layouts/language' %>
                    </div>
                  </div>
                  <!--end::Menu-->
                </div>
                <!--end::Notice-->
                <!--              <div class="mt-10">-->
                <!--                <a href="<%#=onboarding_path %>" class="btn btn-sm btn-primary"><%#= t('verification.button') %></a>-->
                <!--              </div>-->
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<script>
    $("#preferred_locale_hidden").val(getUrlParameter('locale') ? getUrlParameter('locale') : (getCookie('locale') ? getCookie('locale') : "en"));
</script>

</body>
</html>