config/routes.rb
  match '/chat/:id', :to => 'chat#index', via: [:get], as: :chat_index
  match '/sms_campaign', :to => 'chat#sms', via: [:get], as: :sms_chat
  match '/send_sms_campaign', :to => 'chat#send_sms', via: [:post], as: :sms_send
  match '/fetch_agenda_slots', :to => 'chat#fetch_available_slots', via: [:post], as: :widget_slots
  match '/fetch_agenda_slots_for_schedule', :to => 'chat#fetch_available_slots_for_schedule', via: [:post], as: :widget_slots_for_schedule
  match '/validate_customer', :to => 'chat#validate_customer', via: [:post], as: :customer_verify
  match '/get_mandatory_question', :to => 'chat#get_mandatory_question', via: [:post], as: :get_mandatory_question
  match '/create_new_customer', :to => 'chat#create_customer', via: [:post], as: :create_customer_widget
  match '/update_customer', :to => 'chat#update_customer', via: [:post], as: :update_customer_widget
  match '/book_appointment', :to => 'chat#book_appointment', via: [:post], as: :book_appointment
  match '/cancel_appointment', :to => 'chat#cancel_appointment', via: [:post], as: :cancel_appointment
  match '/book_appointment_for_schedule', :to => 'chat#book_appointment_for_schedule', via: [:post], as: :book_appointment_for_schedule
  match '/linked_services_or_resources', :to => 'chat#linked_services_or_resources', via: [:post], as: :linked_services_or_resources
  match '/linked_questions', :to => 'chat#linked_questions', via: [:post], as: :linked_questions

  match '/pre_confirmation/cancelation/:id', :to => 'pre_confirmation#cancelation', via: [:get], as: :pre_confirmation_cancelation
  match '/pre_confirmation/acceptance/:id', :to => 'pre_confirmation#acceptance', via: [:get], as: :pre_confirmation_acceptance

  resources :pricing, only: [:index]
  # do
    # collection do
    #   get :pay_via_gocardless, as: :gocardless
    #   get :finalize_payment, as: :finalize_payment
    # end
  # end

  resources :plans, only: %i[index]

  # devise_for :clients, path: '',
  #           controllers: {sessions: "clients/sessions", registrations: "clients/registrations"},
  #           path_names:   { sign_in: 'login', sign_up: 'signup', edit: "settings/edit"}
  get '/auth/cronofy/callback', to: 'webhooks#cronofy'
  get '/cronofy/auth_callback', to: 'agenda_connect#connect'
  post '/cronofy/notification_callback/:client_id', to: 'notification#add_notification', as: :notification_callback
  post '/notification/get_notification', to: 'notification#get_notification'
  post '/chargebee_event_handler', to: 'webhooks#chargebee_event_handler', as: :chargebee_event_handler
  post '/event_trigger', to: 'webhooks#cronofy_event_trigger', as: :cronofy_event_trigger
  post '/status_callback', to: 'webhooks#twilio_status_callback', as: :status_callback

  resource :agenda_app do
    post :save_agenda_info
    post :save_agenda_info_old
    post :create_new_agenda
    post :get_calendars_of_agenda
    post :save_mobminder
    post :save_timify
  end

  # get 'activity', to: 'activity#index', as: 'activity_index'

  # resources :stats, path: '/activity/stats', only: [:index] do
  #   collection do
  #     match :search_stats, via: [:post, :get]
  #   end
  # end

  # resources :customers, path: 'activity/customers' do
  #   collection { post :import }
  # end
  # resource :activity, only: [:index]
  # resource :activity, only: [] do
  #   collection do
  #     resources :reports, only: [] do
  #       # collection do
  #       #   match :index, via:[:get, :post]
  #       # end
  #     end
  #   end
  # end

  resources :activity do
    collection do
      resources :reports, only: [:index] do
        collection do
          match :calls, via:[:get, :post]
          match :sms_list, via:[:get, :post], as: :sms
          match :url, via:[:get, :post]
          match :aggregates, via:[:get, :post]
          post :create_portal_session
          post :logout_portal_session
        end
      end
      resources :customers do
        collection { post :import }
        collection { post :get_contact }
        collection { post :send_phone_info }
        # post "exception_list" => "customers#exceptions"
      end
    end
  end

  match 'customers/exception_list' => 'customers#exceptions', :via => :post
  match 'customers/delete_multiple' => 'customers#destroy_multiple', :via => :post

  namespace :api, defaults: { format: :json } do
    scope :v1 do
      resources :sessions, only: [:create]
      resources :resources, only: [:index]
      resources :services, only: [:index]
      resources :preferences, only: [:index]
      resources :availability, only: [:index]
      resources :appointments, only: [:index, :create, :update, :destroy]
      resources :templates, only: [:index, :create]
      resources :customers, only: [:index, :create] do
        collection do
          match :auth_consumer, via: [:get, :post]
        end
      end
      get '/sessions', to: 'sessions#read'
      post '/send_email', to: 'sessions#send_email'
    end
  end

  resources :contact_us
  resources :clients do
    resources :ivrs do
      collection do
        get :change_ivr
      end
    end
    member do
      match :billing, via: [:post, :get]
      match :scheduling_appoinments_show, via: [:post, :get]
      match :edit_text, via: [:post, :get]
    end
    collection do
      patch :agenda_sign_up
      match :call_forwarding, via: [:post, :get]
      match :phone, via: [:get, :post]
      post :change_menu
      post :update_gtm_trigger
      post :get_client_detail
      get :my_ivrs
    end
  end

    resources :timify_credential, only: [] do
      collection do
        get :timify_cred
        post :timify_cred
        post :new_account_cred
        get :same_client
        get :different_client
        get :cancel_process
        get :check_timify_connection
        post :disconnect_timify_connection
      end
    end

  resources :integrations, only: [:index] do
    collection do
      match :connect_your_agenda, via:[:get, :post]
      match :select_agenda, via:[:get, :post]
      match :select_mobminder, via:[:get, :post]
      match :select_timify, via:[:get, :post]
      match :phone, via:[:get, :post]
      match :sms, via:[:get, :post]
      match :get_sms_channel, via:[:get]
      match :alpha_sms, via:[:get, :post]
      match :disconnect_calendar, via:[:post]
      match :update_calendar, via:[:post]
      match :update_conflict, via:[:post]
      match :change_dataserver, via:[:post]
      match :inbound_sms, via:[:post]
    end
  end

  resources :appoinments_scheduling, only: [:index, :create] do
    collection do

      get '/widget_preference/:ivr_id', to: 'appoinments_scheduling#widget_preference', as: 'widget_preference'
      get '/assistant_preference/:ivr_id', to: 'appoinments_scheduling#assistant_preference', as: 'assistant_preference'
      get '/general_preference/:ivr_id', to: 'appoinments_scheduling#general_preference', as: 'general_preference'
      get :get_resources
      match :assistant_preference, via:[:get]
      match :service_and_resource, via:[:get, :post]
      match :custom_texts, via:[:get, :post]
      match :save_language, via:[:post]
      match :save_business_hours, via:[:post]
      match :save_welcome_message, via:[:post]
      match :save_announce, via:[:post]
      match :save_followup, via:[:post]
      match :save_preferences, via:[:post]
      match :save_custom_texts, via:[:post]
      match :save_phone_menu, via:[:post]
      match :save_phone_menu_extentions, via:[:get, :post]
      match :new_phone_menu_extention, via:[:get]
      match :get_phone_menu_extention, via:[:get]
      match :get_extension, via:[:get]
      match :save_extension, via:[:post]
      match :delete_phone_menu_extension, via:[:post]
      match :remove_extension, via:[:post]
      match :set_default_extension, via:[:post]
      match :save_widget_setting, via:[:post]
      match :save_booking_option, via:[:post]
      match :save_branding, via:[:post]
      match :save_general_setting, via:[:post]
    end
  end

  resources :schedule_event do
    collection do
      post :get_events
      post :get_event_detail_info
      post :delete_event
      post :save_setting
      post :save_business_hours
      post :get_time_list
    end
  end

  resources :availablities do
    collection do
      post :save_schedule
      post :clone_schedule
      post :set_as_default
      post :delete_schedule
      post :save_availability
    end
  end

  resources :resources do
    member do
      put :toggle_enabled, as: :toggle_enabled
      post :change_enabled, as: :change_enabled
      post :get_calendar_info_of_resource
    end

    collection do
      post :get_availablities
      post :get_calendar_info_of_default
      post :update_resource
    end
  end
  resources :services do
    member do
      put :toggle_enabled, as: :toggle_enabled
      put :toggle_service_options_enabled, as: :toggle_service_options_enabled
    end

    collection do
      get '/new', to: 'services#new', as: :new_service
      get '/new_event/:ivr_id', to: 'services#new_event', as: :new_event
      get '/edit_event/(:id)', to: 'services#edit_event', as: :edit_event
      post :update_ordering, as: :update_ordering
      post :get_resources_of_selected_service, as: :get_resources_of_selected_service
      post :save_agenda_service_resource
      post :get_availablities
      post :save_as_schedule
      post :save_automation
      post :get_automation
      post :save_question
      post :automation_enabled
      post :get_slot_example
      post :number_list
      post :get_phone_countries
      post :order_number
      post :buy_no_address_number
      post :set_phone_type_of_ivr
      post :set_read_tutorial
      get :get_dependencies
      get '/(:filter)', to: 'services#index', as: :services
    end
  end

  resources :profiles do
    collection do
      post :close_account
      post :update_locale
      get :closed_account
    end
  end

app/helpers/report_helper.rb
module ReportHelper

  def short_url_customer(short_url)
    number = short_url.owner.to.sub('+', '')
    @customer ||= current_client.customers.find_by(phone_number: number)
  end
end

app/views/reports/_header.html.erb
<%= stylesheet_link_tag    'datatables.bundle', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'datatables.bundle', 'data-turbolinks-track' => true %>

<div class="toolbar" id="kt_toolbar">
  <!--begin::Container-->
  <div id="kt_toolbar_container" class="container-fluid d-flex flex-stack">
    <!--begin::Page title-->
    <div data-kt-swapper="true" data-kt-swapper-mode="prepend" data-kt-swapper-parent="{default: '#kt_content_container', 'lg': '#kt_toolbar_container'}"
         class="page-title d-flex align-items-center flex-wrap me-3 mb-5 mb-lg-0">
      <!--begin::Title-->
      <h1 class="d-flex align-items-center text-dark fw-bolder my-1 fs-3"><%= t('sidebar_menu.reports') %></h1>
      <!--end::Title-->
    </div>
    <!--end::Page title-->
    <!--begin::Actions-->
    <div class="d-flex align-items-center py-1"></div>
    <!--end::Actions-->
  </div>
  <!--end::Container-->
</div>

app/views/reports/_tabs.html.erb
<div class="card-header card-header-stretch px-5 px-md-9">
  <div class="card-toolbar">
    <ul class="nav nav-stretch nav-line-tabs nav-line-tabs-2x border-transparent flex-nowrap">
      <!--begin::Nav item-->
      <li class="nav-item">
        <a class="nav-link text-active-primary me-6 <%= 'active' if report_type == 'call_report' %>" href="<%= calls_reports_path %>"><%= t('stats.heading') %></a>
      </li>
      <!--end::Nav item-->
      <!--begin::Nav item-->
      <li class="nav-item">
        <a class="nav-link text-active-primary me-6 <%= 'active' if report_type == 'sms_report' %>" href="<%= sms_reports_path %>"><%= t('sms_stats.heading') %></a>
      </li>
      <!--end::Nav item-->
      <!--begin::Nav item-->
      <li class="nav-item">
        <a class="nav-link text-active-primary me-6 <%= 'active' if report_type == 'click_report' %>" href="<%= url_reports_path %>"><%= t('url_stats.heading') %></a>
      </li>
      <!--end::Nav item-->
    </ul>
  </div>
  <div class="card-toolbar"></div>
</div>

app/views/reports/index.html.erb
<% content_for :content_head_toolbar do %>
  <div></div>  
<% end %>

app/views/reports/url.html.erb
<%= render 'reports/header' %>

<div class="post d-flex flex-column-fluid" id="kt_post">
  <!--begin::Container-->
  <div id="kt_content_container" class="container-fluid">
    
    <div class="card mb-0">
      <%= render 'reports/tabs', report_type: 'click_report' %>
      <div class="card-body px-5 px-md-9 py-5">
        <!--begin::Wrapper-->
        <div class="d-sm-flex flex-stack mb-5">
          <!--begin::Search-->
          <div class="d-flex align-items-center position-relative my-1 mb-6 mb-sm-0">
            <i class="bi bi-search position-absolute ms-6"></i>
            <input type="text" data-kt-docs-table-filter="search" class="form-control form-control-solid w-250px ps-15" placeholder="<%= t('stats.search_report') %>"/>
          </div>
          <!--end::Search-->

        </div>
        <!--end::Wrapper-->

        <!--begin::Datatable-->
        <table id="kt_datatable_click_report" class="table table-row-dashed gy-5">
          <thead>
          <tr class="text-start text-uppercase gs-0">
            <th class="align-top"><%= I18n.t('url_stats.short_url') %></th>
            <th class="align-top"><%= I18n.t('url_stats.target_url') %></th>
            <th class="align-top"><%= I18n.t('url_stats.sent_on') %></th>
            <th class="align-top"><%= I18n.t('url_stats.clicks') %></th>
            <th class="align-top"><%= I18n.t('url_stats.last_clicked_at') %></th>
            <th class="align-top"><%= I18n.t('url_stats.contact_name') %></th>
            <th class="align-top"><%= I18n.t('url_stats.contact_number') %></th>
          </tr>
          </thead>
          <tbody></tbody>
        </table>
        <!--end::Datatable-->
      </div>
    </div>
  </div>
  <!--end::Container-->
</div>

<script>
    (function () {
        // Class definition
        var KTDatatablesServerSide = function () {
            // Mock
            var dataSet = <%= raw @url_data.to_json %>;

            // Shared variables
            var table;
            var dt;

            // Private functions
            var initDatatable = function () {
                dt = $('#kt_datatable_click_report').DataTable({
                    searchDelay: 500,
                    order: [[0, 'asc']],
                    select: {
                        style: 'os',
                        selector: 'td:first-child',
                        className: 'row-selected'
                    },
                    data: dataSet,
                    columns: [
                        {data: 'ShortURL'},
                        {data: 'TargetURL'},
                        {data: 'SentOn'},
                        {data: 'Clicks'},
                        {data: 'LastClickedAt'},
                        {data: 'ContactName'},
                        {data: 'ContactNumber'},
                    ],
                    columnDefs: [
                        {
                            targets: [0, 1],
                            render: function (data) {
                                return `<a href="${data}">${data}</a>`;
                            }
                        },
                        {
                            targets: 3,
                            render: function (data) {
                                return `<strong>${data}</strong>`;
                            }
                        },

                    ],
                    initComplete: function () {
                        KTMenu.createInstances();
                    }
                });

                table = dt.$;

                // Re-init functions on every table re-draw -- more info: https://datatables.net/reference/event/draw
                dt.on('draw', function () {
                    KTMenu.createInstances();
                });
            };

            // Search Datatable --- official docs reference: https://datatables.net/reference/api/search()
            var handleSearchDatatable = function () {
                const filterSearch = document.querySelector('[data-kt-docs-table-filter="search"]');

                filterSearch.addEventListener('keyup', function (e) {
                    dt.search(e.target.value).draw();
                });
            };

            // Public methods
            return {
                init: function () {
                    initDatatable();
                    handleSearchDatatable();

                    $('.kt_new_added_tooltip').each(function (i, el) {
                        const newTooltip = new bootstrap.Tooltip(el);
                    });
                }
            };
        }();

        // On document ready
        KTUtil.onDOMContentLoaded(function () {
            KTDatatablesServerSide.init();
        });
    })();

</script>
<style>
    #kt_datatable_click_report_wrapper {
        margin-top: -10px;
    }
    #kt_datatable_click_report_filter {
        margin-top: -48px;
        display: none;
    }
    div#kt_datatable_click_report_length {
        display: none;
    }
</style>